apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "datalake.hiveservice.fullname" . }}
  labels:
    app: {{ template "datalake.hiveservice.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgresql:5432/metastore</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>hive</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>hive</value>
      </property>
      <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.execution.engine</name>
        <value>spark</value>
      </property>
      <property>
        <name>fs.alluxio.impl</name>
        <value>alluxio.hadoop.FileSystem</value>
        <description>The Alluxio FileSystem (Hadoop 1.x and 2.x)</description>
      </property>
      <property>
        <name>fs.AbstractFileSystem.alluxio.impl</name>
        <value>alluxio.hadoop.AlluxioFileSystem</value>
        <description>The Alluxio AbstractFileSystem (Hadoop 2.x)</description>
      </property>
      <property>
        <name>fs.defaultFS</name>
        <value>alluxio://sandbox01.p02.eng.sjc01.qualys.com:19998</value>
      </property>
      <property>
        <name>spark.master</name>
        <value>spark://spark-master:6066</value>
      </property>
      <property>
        <name>spark.eventLog.dir</name>
        <value>alluxio://sandbox01.p02.eng.sjc01.qualys.com:19998/sparkeventLog</value>
      </property>
      <property>
        <name>spark.home</name>
        <value>/opt/spark</value>
      </property>
      <property>
        <name>hive.server2.transport.mode</name>
        <value>http</value>
      </property>
      <property>
        <name>spark.executor.memory</name>
        <value>7g</value>
      </property>
      <property>
        <name>spark.driver.memory</name>
        <value>1g</value>
      </property>
      <property>
        <name>spark.executor.memoryOverhead</name>
        <value>384m</value>
      </property>
      <property>
        <name>spark.driver.memoryOverhead</name>
        <value>384m</value>
      </property>
      <property>
        <name>spark.scheduler.minRegisteredResourcesRatio</name>
        <value>0.8</value>
      </property>
      <property>
        <name>alluxio.user.file.readtype.default</name>
        <value>NO_CACHE</value>
      </property>
      <property>
        <name>hive.metastore.schema.verification</name>
        <value>true</value>
      </property>
    </configuration>